---
- hosts: main
  remote_user: root
  tasks:
      - name: Install build-essential and OpenJDK
        apt:
            name: "{{ pkgs }}"
            state: latest
            update_cache: yes
        vars:
          pkgs:
            - build-essential
            - default-jdk
            - openssh-server

      - name: Create hadoop group
        group:
            name: hadoop
            state: present

      - name: Create hduser user and add to hadoop group
        user:
            name: hduser
            group: hadoop

      - name: Create .ssh folder for hduser
        file:
            path: /home/hduser/.ssh
            state: directory

      # - name: Generate SSH key for hduser
      #   command: ssh-keygen -t rsa -P "" -f /home/hduser/.ssh/id_rsa.pub
      #
      # # - name: Copy the SSH key into authorized_keys
      # #   command: mv /home/hduser/.ssh/id_rsa /home/hduser/.ssh/id_rsa.pub
      #
      - name: Touch authorized_keys file
        command: touch /home/hduser/.ssh/authorized_keys && chown hduser:hadoop /home/hduser/.ssh/authorized_keys

      - name: Create authorized_keys file
        file:
            path: /home/hduser/.ssh/authorized_keys
            group: hadoop
            owner: hduser
            state: touch
      #
      # - name: Copy the SSH key into authorized_keys
      #   authorized_key:
      #       user: hduser
      #       key: /home/hduser/.ssh/id_rsa.pub.pub
      #       state: present

      - name: Copy IPv6 configuration (all) into /etc/sysctl.conf
        lineinfile:
            path: /etc/sysctl.conf
            line: net.ipv6.conf.all.disable_ipv6 =1

      - name: Copy IPv6 configuration (default) into /etc/sysctl.conf
        lineinfile:
            path: /etc/sysctl.conf
            line: net.ipv6.conf.default.disable_ipv6 =1

      - name: Copy IPv6 configuration (lo) into /etc/sysctl.conf
        lineinfile:
            path: /etc/sysctl.conf
            line: net.ipv6.conf.lo.disable_ipv6 =1

      - name: Get Hadoop 3.1.2 binary
        get_url:
            url: http://apache.mirror.anlx.net/hadoop/common/hadoop-3.1.2/hadoop-3.1.2.tar.gz
            dest: /home/hduser/hadoop-3.1.2.tar.gz

      - name: Make Hadoop folder
        command: mkdir /home/hduser/hadoop

      - name: Extract Hadoop tarfile
        unarchive:
            src: /home/hduser/hadoop-3.1.2.tar.gz
            dest: /home/hduser/hadoop

      - name: Move Hadoop folder to /usr/local
        command: mv /home/hduser/hadoop/hadoop-3.1.2 /usr/local/hadoop

      - name: Set owner of Hadoop files to hduser
        file:
            path: /usr/local/hadoop
            owner: hduser
            group: hadoop
            recurse: yes

      - name: Insert JAVA_HOME variable into hadoop-env
        lineinfile:
            path: /usr/local/hadoop/etc/hadoop/hadoop-env.sh
            line: export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64

      - name: Make a HDFS directory and set owner to hduser and set permissions
        file:
            path: /app/hadoop/tmp
            state: directory
            owner: hduser
            group: hadoop
            recurse: yes
            mode: 0750

      # - name: Copy Hadoop config files
      #   copy:
      #       src: "{{ config_files }}"
      #       dest: /app/hadoop/etc/hadoop/
      #       owner: hduser
      #       group: hadoop
      #   vars:
      #     config_files:
      #         - core-site.xml
      #         - hdfs-site.xml
      #         - mapred-site.xml

      - name: Copy core-site.xml file
        copy:
            src: core-site.xml
            dest: /app/hadoop/etc/hadoop/
            owner: hduser
            group: hadoop

      - name: Copy hdfs-site.xml file
        copy:
            src: hdfs-site.xml
            dest: /app/hadoop/etc/hadoop/
            owner: hduser
            group: hadoop

      - name: Copy mapred-site.xml file
        copy:
            src: mapred-site.xml
            dest: /app/hadoop/etc/hadoop/
            owner: hduser
            group: hadoop
